### ISSUE TITLE
Failure causes artifacts to not upload

### ISSUE THREAD

**Issue by mhackermsft** [Azure-Samples/jmeter-aci-terraform#11]
During a load test I had some HTTP requests that failed due to the remote system unable to handle the load.  Once the test completed the "Publish Load Testing Results" step shows the error "##[error]There are one or more test failures detected in result files. Detailed summary of published test results can be viewed in the Tests tab." which is expected since some http requests failed.  The issue is the following step which should upload the jMeter results (RESULTS: Publish Load Test Artifacts) does not run due to the prior step's error.    This means there is no way to see the actual jMeter dashboard when any failure occurs.

**Comment by mhackermsft** [comment]
I think we need to add:

` condition: succeededOrFailed()`

In the azure-pipelines.load-test.yml for the publish artifacts step.   This will allow the jMeter artifacts to be stored no matter what the load test outcome is.

**Comment by allantargino** [comment]
Thanks for that @mhackermsft! We were able to reproduce it and we will fix it.
