### ISSUE TITLE
The subscription of 'subscription_id' doesn't exist in cloud 'AzureCloud'

### ISSUE THREAD

**Issue by prabhaharanv** [Azure-Samples/jmeter-aci-terraform#17]
Hi,
ERROR: The subscription of 'subscription_id' doesn't exist in cloud 'AzureCloud'. is thrown at 'Login on Azure CLI' job when running docker pipeline. I have same tenant id for 5 of my azure subscriptions.

**Comment by fedeoliv** [comment]
Hi @prabhaharanv , could you please check what is the value of the `ARM_SUBSCRIPTION_ID` variable in the `JMETER_AZURE_PRINCIPAL` variable group on Azure DevOps? Looks like this value is missing there.

**Comment by prabhaharanv** [comment]
Thanks for the timely response @fernandoBRS. You rightly pointed it out. Now, it works fine :)
