### ISSUE TITLE
JMeter slave creation takes more time with more number of slaves configured

### ISSUE THREAD

**Issue by prabhaharanv** [Azure-Samples/jmeter-aci-terraform#20]
Hi,
When I tried to create more slaves (6 slaves), SETUP: Run Terrafarm Apply task keeps running more than 45 minutes and not finished. When I checked my list of container instances, only one slave was in Running state and rest of the 5 were in Pending state. What could be the issue?
![JMeter slave creation takes more time](https://user-images.githubusercontent.com/45698465/77854023-4702f300-7205-11ea-8488-a8e5f999f4bb.jpg)

**Comment by fedeoliv** [comment]
Hi @prabhaharanv could you please inform in what region your ACI has been provisioned?

**Comment by prabhaharanv** [comment]
@fernandoBRS west europe

**Comment by fedeoliv** [comment]
Thanks for the info @prabhaharanv. Could you please try to deploy in a different region and check if the problem persists?

**Comment by prabhaharanv** [comment]
Not facing this issue with 4 slaves now
