### ISSUE TITLE
Lack of documentation of extensions for Azure DevOps and add parameters

### ISSUE THREAD

**Issue by Guilhermeslucas** [Azure-Samples/jmeter-aci-terraform#21]
Hello everyone, how are you? So, I was a heavy user from this project on the last weeks (thanks a lot for that) and there are two things that I took some time to find since the docs doesn't say anything about:
- In order to use Azure cli with Azure DevOps, you need to install an extension for that.
- The command to add parameters on the pipelines seem wrong, since default value is also a mandatory argument on the command line.

I'll open a PR in order to fix this things I told. Do you it makes sense?
Thanks a lot, again!

**Comment by Guilhermeslucas** [comment]
Actually the docs says about the Azure DevOps extension, Ill just try to make it more clear, if you may!

**Comment by allantargino** [comment]
Hi @Guilhermeslucas,
Thanks for using the sample!

About that part:
> The command to add parameters on the pipelines seem wrong, since default value is also a mandatory argument on the command line.

I was able to add variables to pipeline without a default value, and this also seems to be the expected behavior: https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/variable?view=azure-cli-latest#required-parameters

What happens when you try to run:
```shell
az pipelines variable create --pipeline-name $PIPELINE_NAME_JMETER --name TF_VAR_JMETER_JMX_FILE --allow-override
```

**Comment by Guilhermeslucas** [comment]
I was getting the message 
```
Default value is required. Add it using --default-value
```
But I am not getting this error anymore, following each step you say on the docs, so I feel its cool!
Thanks!
