### ISSUE TITLE
JMeter Master CPU Utilization is above 90%

### ISSUE THREAD

**Issue by prabhaharanv** [Azure-Samples/jmeter-aci-terraform#26]
When I set up a cluster with below, my JMeter Master CPU utilization is 3.77 GB which is above 90% of the available resource. I cant create a master with more CPU since 4 GB is the maximum allowed CPU. I have the cluster created in West Europe Azure region. Moreover, Neither JMeter Artefacts are generated nor Pipeline run results. So, I dont have any detailed logs to analyse exactly what caused the failure
![JMeter Master issue](https://user-images.githubusercontent.com/45698465/78269984-e25ad780-7527-11ea-8e6e-5b4db0242c07.jpg)
 
My load profile: 800 Concurrent Threads with 200 seconds ramp up time and 300 seconds run duration
Master: 4 CPU, 16 GB Memory;
4 Slaves each with 4 vCPU, 16 GB Memory

**Comment by prabhaharanv** [comment]
Can someone please take a look at this issue?

**Comment by allantargino** [comment]
Do you have another screenshot of the end of the controller logs?
Can you please paste all the log here?

**Comment by allantargino** [comment]
Please reopen if you still have this issue.
