### ISSUE TITLE
[question] Is there any way to use this with fixed IPs?

### ISSUE THREAD

**Issue by johnvlittle** [Azure-Samples/jmeter-aci-terraform#28]
the website we want to test is not public, and we have to whitelist IPs. for this reason we cant use the normal azure load tests services, in addition to the azure load test jmeter offering being too limited (no custom listeners or samplyers, and only jmeter 3.2).

Does this tool have any way to use it with fixed outgoing IPs?

**Comment by allantargino** [comment]
Hey,

The JMeter workers are deployed in a private VNET and you can define both VNET and Subnet IP ranges: https://github.com/Azure-Samples/jmeter-aci-terraform/blob/2584ef3c6777bf1ddfbdff8f4ae081042dc5b618/terraform/variables.tf#L16-L24

Does this help you?

**Comment by allantargino** [comment]
Closing this issue @johnvlittle, please let me know if you still have questions.
