### ISSUE TITLE
Prerequisites: ACR needs admin enabled

### ISSUE THREAD

**Issue by ignaciofls** [Azure-Samples/jmeter-aci-terraform#57]
When noting the prerequisites please add that ACR needs admin access enabled. Instructions for both CLI and UI are here: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#admin-account

Otherwise great repo, I forked it to tailor it for Azure Cognitive Search latency and concurrency tests

**Comment by allantargino** [comment]
Thanks for the issue, @ignaciofls!
I am glad it was useful 😄
