### ISSUE TITLE
Jmeter Version

### ISSUE THREAD

**Issue by garyc0221** [Azure-Samples/jmeter-aci-terraform#62]
Hello,

I was wondering can anybody help me. Currently when launching the pipeline it is using jmeter version 5.1.1 is there a way to get a newer version. I can see that you are pulling from justb4/jmeter although the current version they are using is 5.4.
Thanks

**Comment by cmelo05** [comment]
@garyc0221, the base image `justb4/jmeter` is at version 5.1.1, as you can see [here](https://github.com/Azure-Samples/jmeter-aci-terraform/blob/18d10124d69d60e2a1c8d342fef52e4b40ef336b/docker/Dockerfile#L1).

If you update your Dockerfile, you should be able to run other JMeter versions

**Comment by cmelo05** [comment]
> Hello,
> 
> I was wondering can anybody help me. Currently when launching the pipeline it is using jmeter version 5.1.1 is there a way to get a newer version. I can see that you are pulling from justb4/jmeter although the current version they are using is 5.4.
> Thanks

@garyc0221, the base image justb4/jmeter is at version 5.1.1, as you can see [here](https://github.com/Azure-Samples/jmeter-aci-terraform/blob/18d10124d69d60e2a1c8d342fef52e4b40ef336b/docker/Dockerfile#L1).

If you update your Dockerfile, you should be able to run other JMeter versions
