### ISSUE TITLE
Issue with jmeter extra arguments

### ISSUE THREAD

**Issue by shivam201** [Azure-Samples/jmeter-aci-terraform#64]
to achieve this jmeter command - 
jmeter -n -t "sample.jmx" -Jemail=*** -Jpassword=*** -Juser.classpath="somejar.jar" -l results.jtl -j log.txt

I updated main.tf line 161.
"cd /jmeter; /entrypoint.sh -n -J server.rmi.ssl.disable=true -t ${var.JMETER_JMX_FILE} -l ${var.JMETER_RESULTS_FILE} -e -o ${var.JMETER_DASHBOARD_FOLDER} -R ${join(",", "${azurerm_container_group.jmeter_workers.*.ip_address}")} ${var.JMETER_EXTRA_CLI_ARGUMENTS}"

to 
"cd /jmeter; /entrypoint.sh -n -J server.rmi.ssl.disable=true -t ${var.JMETER_JMX_FILE} -l ${var.JMETER_RESULTS_FILE} -e -o ${var.JMETER_DASHBOARD_FOLDER} -R ${join(",", "${azurerm_container_group.jmeter_workers.*.ip_address}")} ${var.JMETER_EXTRA_CLI_ARGUMENTS} -Jemail=${var.EMAIL} -Jpassword=${var.PASSWORD} -Juser.classpath=${var.SOMEJAR} '

but at time of execution this parameter is not getting invoked.
Can anyone let me know if i am doing anything wrong in this

**Comment by wenbya** [comment]
@shivam201 same issue with me. have you resolved it? help needed really

**Comment by shivam201** [comment]
Hi yes it's resolved.
U need to mention the same parameter 2 places in main.tf
One in the line 115 mention the same parameter and second one in line 161 line.
Hope that resolve you issue.
