### ISSUE TITLE
The tests gives an error after 53 minutes

### ISSUE THREAD

**Issue by renetitulaer** [Azure-Samples/jmeter-aci-terraform#65]
Hi all,

I have a test: 2 users are running about 25 rest calls for 50 times. I think that this takes about almost 1 hour but it breaks before it ends.

It runs fine if I execute the same jmx file for 5 users 20 times.
my tests run fine for 20 minutes but when I want to run it for about an hour I get this error:
TEST: Wait Test Execution
-> 
/usr/bin/az account set --subscription 4fe8cc8e-d9ed-4b5a-91c4-e2471d71e675
/bin/bash /home/vsts/work/_temp/azureclitaskscript1622822721406.sh
Fri Jun  4 16:05:24 UTC 2021: Started!
Fri Jun  4 16:05:25 UTC 2021: Still Running...
...
Fri Jun  4 16:58:57 UTC 2021: Still Running...
##[error]The operation was canceled.
Finishing: TEST: Wait Test Execution

So the test was actually running 53 minutes.

It happened before: 
usr/bin/az account set --subscription 4fe8cc8e-d9ed-4b5a-91c4-e2471d71e675
/bin/bash /home/vsts/work/_temp/azureclitaskscript1622816548628.sh
Fri Jun  4 14:22:31 UTC 2021: Started!
Fri Jun  4 14:22:32 UTC 2021: Still Running...
Fri Jun  4 14:22:54 UTC 2021: Still Running...
...

Fri Jun  4 15:15:54 UTC 2021: Still Running...
##[error]The operation was canceled.
Finishing: TEST: Wait Test Execution

So also 53 minutes.

Does anybody know debug this issue?
So 53 minutes also

**Comment by allantargino** [comment]
Hi @renetitulaer 
Please check the limitations section: https://github.com/Azure-Samples/jmeter-aci-terraform#limitations

> *Load Test duration*: Please note that for Microsoft hosted agents, you can have pipelines that runs up to 1 hour (private project) or 6 hours (public project). You can have your own agents to bypass this limitation.

**Comment by renetitulaer** [comment]
Thanks a lot Allan for the quick response!
