### ISSUE TITLE
Readme not clear on what kind of tests is this sample performing

### ISSUE THREAD

**Issue by agowdamsft** [Azure-Samples/jmeter-aci-terraform#8]
I am looking for a business context of when I should use this sample (e.g. doing unit tests, integration tests using http, or load testing for messaging system and performing). This info will help me to decide when to use this.

**Comment by mhackermsft** [comment]
jMeter does load testing

**Comment by allantargino** [comment]
Hi @agowdamsft,
Thanks for the input. We added some additional notes explicating that we do load testing in general, not tied to a specific scenario. For instane:
> Scalable cloud load/stress testing pipeline solution with Apache JMeter and Terraform to dynamically provision and destroy the required infrastructure on Azure.
Let us know if we can improve it. Thanks!
